[package]
name = "poker_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.23"
strum_macros = "0.23"
rand = "0.8.0"
clap = "2"
pickledb = "0.4.1"
#text_io = "0.1.9"
